### ISSUE TITLE
How to include harapi.js into an external web page?

### ISSUE THREAD

**Issue by xmhubj** [devtools-html/har-export-trigger#1]
I saw the **How To Use** guidance which says need to include `harapi.js` in to the web page, but how can I include this javascript into an external website, like https://www.google.com.

Can `harapi.js` be added into the `content_scripts` of manifest.json? 

> Quote from https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts
```
Instructs the browser to load content scripts into web pages whose URL matches a given pattern.
```

**Comment by xmhubj** [comment]
I was trying to run the harpai function in the firefox console, and then ran 
```
HAR.triggerExport().then(harLog => {
  console.log(harLog);
});
```
did not see the har log in the console output.

**Comment by janodvarko** [comment]
The `harapi.js` file is now injected into every page automatically.

@xmhubj Can you please try this branch and let me know if it works for you?
https://github.com/devtools-html/har-export-trigger/tree/harapi

Also, note that the Network panel needs to be selected at least once to make the HAR API work.
This limitation will be fixed soon in: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1436665

Honza

**Comment by xmhubj** [comment]
OK, I'll test it later today.

**Comment by xmhubj** [comment]
Tried with the branch, seems still not working. My Firefox version as:

```
Application Basics
------------------

Name: Firefox
Version: 59.0b7
Build ID: 20180205211730
Update Channel: beta
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
OS: Linux 3.13.0-85-generic
Multiprocess Windows: 1/1 (Enabled by default)
Web Content Processes: 3/4
Stylo: content = true (enabled by default), chrome = false (disabled by default)
Google Key: Found
Mozilla Location Service Key: Found
Safe Mode: false
```

The steps what I tried:

1. Enable add-on debugging and load add-on from file.
2. Open a new tab and `shift+F5` to launch devtools.
3. Switch to `network` tab in devtools panel.
4. Navigate to https://www.google.com, I can see network traffics in network tab.
5. Switch to `console` tab, and run `HAR.triggerExport().then(harLog => {console.log(harLog)});`

Only see a promise returned in `pending` status, without Har log.

![harexport](https://user-images.githubusercontent.com/15373664/36026977-47a1d660-0dd4-11e8-849c-fe88cd1e2e84.jpg)

**Comment by xmhubj** [comment]
Noticed that Firefox 60+ should be used to run the add-on, but I didn't find the Firefox 60 available from http://ftp.mozilla.org/pub/firefox/releases/

**Comment by soulgalore** [comment]
@xmhubj you need to run Nightly to get 60.

**Comment by janodvarko** [comment]
@xmhubj Does it work for you with Fx60?
Honza

**Comment by janodvarko** [comment]
Note that Fx60 is currently available as Firefox Nightly
https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

Fx60 goes beta 3/12, see release schedule:
https://wiki.mozilla.org/RapidRelease/Calendar

@xmhubj: should I close this bug or wait?

Honza

**Comment by xmhubj** [comment]
@janodvarko I was on vacation(Chinese Spring Festival), will try it today. Sorry for delayed response.

**Comment by xmhubj** [comment]
Tried with `Mozilla Firefox 60.0a1` nightly build on Linux x86-64, now I can get the log object right after promise returned. Thanks. We can close this one.

**Comment by janodvarko** [comment]
Thanks for the update!
Honza
