### ISSUE TITLE
entry.time is null

### ISSUE THREAD

**Issue by soulgalore** [devtools-html/har-export-trigger#11]
Hi @janodvarko 
I guess this is an upstream issue: the entry.time field in the HAR is always null (but entry.timings is populated):

```
startedDateTime: '2018-02-27T22:41:41.846+01:00',
  time: null,
  timings: 
   { blocked: 1,
     connect: 0,
     dns: 0,
     receive: 12,
     send: 0,
     ssl: 0,
     wait: 36 }
```

Best
Peter

**Comment by janodvarko** [comment]
I created Bugzilla report for this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1441761

Honza

**Comment by janodvarko** [comment]
Fixed in Firefox 60
Honza
