### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by farooqrahman** [devtools-html/har-export-trigger#12]
Hi,

Many thanks for providing this awesome plugin, I have verified this plugin and it is meeting our expectations. We want to use this plugin in our production, can you please let us know how to get the license to use this plugin? When can we expect the official release of this plugin?

Thanks.

**Comment by janodvarko** [comment]
I added a license file (MPL2)
https://github.com/devtools-html/har-export-trigger/commit/e38b505ec1a2915bc2edfceb4a9315a55e3e3d75

I am waiting for 61 to go to beta/feedback and then I'll upload the extension on AMO.
(should happen in couple of weeks)

Honza

**Comment by farooqrahman** [comment]
Hi

Can you please upload the extension on AMO. I searched in the AMO but I could not find it.

Thanks,
Farooq.

**Comment by janodvarko** [comment]
Done

You should be able to download it from here:
https://addons.mozilla.org/en-US/firefox/addon/har-export-trigger/

Honza
