### ISSUE TITLE
Inject harapi.js in page (without browser add-on and without enabling network tab)

### ISSUE THREAD

**Issue by leadwire-apm** [devtools-html/har-export-trigger#15]
Hi, 

I'm using a Java API to inject custom javascript in web pages  (in order to collect navigation timing information). The javascript plugin sends back this data to my server.

Can I use the har-export-trigger this way ?

Regard,
Wassim

**Comment by janodvarko** [comment]
Yes, HARExportTrigger exposes HAR API into the page content and you can consume it by your script.
Honza

**Comment by leadwire-apm** [comment]
Ok for consuming data, but how the HTTP tracking backend gets initialized ?

**Comment by janodvarko** [comment]
DevTools Toolbox needs to be opened.
Honza

**Comment by janodvarko** [comment]
@leadwire-apm I am closing this report, but feel free to reopen or file new one if you experience any trouble!

Thanks,
Honza
