### ISSUE TITLE
The  README gives no clue about how to install this extension

### ISSUE THREAD

**Issue by JonathanRRogers** [devtools-html/har-export-trigger#2]
There is a page on addons.mozilla.org called "HAR Export Trigger": https://addons.mozilla.org/en-US/firefox/addon/har-export-trigger/ However, that is the old version which doesn't work on Firefox Quantum. How does one install this new version on Firefox 60?

**Comment by soulgalore** [comment]
@JonathanRRogers you can try it out by using [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) and then you can configure which FF version you want to use.

**Comment by JonathanRRogers** [comment]
I'm sure it's obvious to those familiar with Firefox extension development, but there's a first time for everyone. I eventually figured out how to build the extension after much Googling and trial and error. How about adding the link to the README and strict_min_version to the manifest and save the next person several hours of frustration?

**Comment by janodvarko** [comment]
Good point, readme file updated.

https://github.com/devtools-html/har-export-trigger/commit/5aa1bde375c467bb8f8591c0d35f317523f5c1a5

Let me know if it's ok now or if you think that more information should be added.

Thanks for the report!

Honza
