### ISSUE TITLE
Retrieving HAR object/string in Selenium

### ISSUE THREAD

**Issue by gmichels** [devtools-html/har-export-trigger#21]
Hello

Sorry if this is the wrong place to ask for this, however I can't find a way to return the HAR string back into Selenium. I can dump it into the console per the instructions, however no matter what I try, I can't get it back via webdriver.

I found https://github.com/firebug/har-export-trigger/issues/9 which seems to be what I need, but I can't make it to work.

Any clues?

Thank you

**Comment by soulgalore** [comment]
Hi @gmichels 
[this](https://github.com/sitespeedio/browsertime/blob/master/lib/firefox/webdriver/firefoxDelegate.js#L38-L56) is what it looks like when we get the HAR from the new export trigger in Browsertime. You need to execute async JavaScript through Selenium and then take care of the result when it's finished. Does that example help?

Best
Peter

**Comment by gmichels** [comment]
Hi @soulgalore, thanks a lot for the pointer, it worked perfectly per the solution you provided. Appreciate the speedy response.
