### ISSUE TITLE
Trigger HAR export from Marionette: "ReferenceError: HAR is not defined"

### ISSUE THREAD

**Issue by renghardt** [devtools-html/har-export-trigger#27]
Hello,

I'm trying to use har-export-trigger using Firefox Marionette, with Firefox 61.0.2 and har-export-trigger-0.6.1. I'm using the Python marionette_client (https://marionette-client.readthedocs.io/en/master/index.html).
When trying to call any function of the HAR API, I get "ReferenceError: HAR is not defined".
Through Selenium/geckodriver, it works.
Calling other Javascripts, e.g., "return window.performance.timing.navigationStart", works as well, from both Selenium and Marionette.

**To reproduce**:
1. Open Firefox with -marionette option, install HAR-Export-Trigger plugin if not previously done.
2. Install marionette_driver, see above (Python2!)
3. Open python2 console, then:
`from marionette_driver.marionette import Marionette` 
`client = Marionette(host='localhost', port=2828)`
`client.start_session()`
`client.navigate("http://www.debian.org")`
`result = client.execute_script("foo = HAR.triggerExport().then( result => { return result;}); return foo;")`

**Expected result**:
getting back the HAR as a string to "result" variable

**Actual result**:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/marionette_driver/marionette.py", line 1717, in execute_script
    rv = self._send_message("WebDriver:ExecuteScript", body, key="value")
  File "/usr/local/lib/python2.7/dist-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/marionette_driver/marionette.py", line 741, in _send_message
    self._handle_error(err)
  File "/usr/local/lib/python2.7/dist-packages/marionette_driver/marionette.py", line 765, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
marionette_driver.errors.JavascriptException: ReferenceError: HAR is not defined
stacktrace:
	@<stdin>:1:15
	@<stdin>:1:2

Now I think this has something to do with the Sandbox that Marionette executes Javascript in, but adding "new_sandbox=False" to the execute_script command does not help. Neither does trying to use "window.HAR.triggerExport()" instead of the global "HAR", which seems to be defined on the browser Javascript console, but from Marionette it gives me a "TypeError: window.HAR is undefined"

Geckodriver seems to work around this somehow: https://github.com/mozilla/geckodriver/issues/1067

Any ideas how to get access to the HAR API from the marionette client would be greatly appreciated!

**Comment by renghardt** [comment]
Trying to dig into this problem more:
I don't think I'm calling the export too soon, I can do it minutes or hours after page load, the status never changes.
I opened the Browser Toolbox to debug the plugin, but I do not get any output from har-export-trigger there.
However, I noticed that I cannot call HAR.triggerExport() from this Browser Toolbox console either, it says "HAR is not defined". In the main browser window in the developer tools console at the bottom, I can call HAR.triggerExport() just fine and get a "Promise". In this case there's no output in the Browser Toolbox console either. 
If I set a breakpoint in the code, e.g., in background.js line 41, if I call HAR.triggerExport() the debugger stops there, but if I try to call it from Marionette, it doesn't. 
So I guess the plugin never gets called due to some sandboxing issue.
Any idea how to find out more about this? (I'm also going to ask some automation people about this.)

**Comment by soulgalore** [comment]
@theri just wanted to make sure that the extension is installed when running Marionette (so that you aren't using a new session without any extensions)? Is it possible to check? I use Geckodriver and in latest version (0.22.0) the installation is broken and the way I found out was I couldn't get the HAR object.  Just a long shot :)

**Comment by renghardt** [comment]
@soulgalore Thanks for taking a guess. But if I can call HAR.triggerExport() just fine from the browser command line (when I press F12) on the very same browser, it should be correctly installed, right? It works this way, it just doesn't work with Marionette.

**Comment by renghardt** [comment]
I got further debugging this, found out that the following works around the "HAR is not defined" error:
`result = client.execute_script("window.foo = HAR.triggerExport().then( result => { return result;}); ", new_sandbox=False, sandbox=None)`

Now my problem is that "window.foo" is a promise that never resolves, and if I call
`result = client.execute_script("return window.foo ")`, Marionette keeps hanging forever.

A kind person from the automation people suggested I execute an async javascript instead:
`self.marionette.execute_async_script("""
  HAR.triggerExport().then(result => arguments[0](result));
""", sandbox=None, new_sandbox=False)`
But again, this keeps hanging forever and never resolves.

If I execute the above window.foo stuff in the browser, it works. Just from Marionette it never resolves.

Any idea how to debug this, e.g., where to set the breakpoint in the Add-on debugger?

My first attempt was to add breakpoints in devtools.js to the first line within onMessage(), onGetHAR(), and onRequestFinished(). 
In all cases (no matter if I call triggerExport from the browser console or from Marionette), the code stops at onMessage for the getHAR message, and in onGetHAR. It does **not** ever reach onRequestFinished(), neither in the Marionette case (where the promise never resolves), nor in the browser console case (where the promise is "fulfilled" the next time I try to access window.foo - even though I never saw the onRequestFinished() breakpoint!)

This is very weird. At this point I'm pretty sure I'm not using the API right.
Any suggestions?

**Comment by renghardt** [comment]
Alright, it seems like my problem resolved itself over night.
I just have to start Firefox with devtools open (-devtools option), and then the following works:

`HARtext = driver.execute_script("window.foo = HAR.triggerExport().then(harLog => { return(harLog); }); return window.foo;", sandbox=None, new_sandbox=False)`

Maybe this points to some issue in the API here, but that's beyond my current scope, so I'm closing this issue.
My scripts are available at https://github.com/theri/web-measurement-tools, just in case anyone's interested.

**Comment by janodvarko** [comment]
Ah, yes, the Developer Toolbox needs to be opened otherwise the Network panel isn't initialized (doesn't exist) and HTTP traffic is not intercepted.

You might see https://github.com/devtools-html/har-export-trigger/issues/13 - thread about how to implement/use HAR export without the Toolbox (wip).

Honza
