### ISSUE TITLE
Any way to speed up the collection of the HAR

### ISSUE THREAD

**Issue by soulgalore** [devtools-html/har-export-trigger#3]
Hi @janodvarko 
first of all, thanks for implementing the trigger, it will be great when we can start using it!

I tried it out (the harapi branch), it works fine for me (I use web-ext to run), but it seems like it takes quite long time to collect the HAR, I wonder if there could be something going on that is wrong.

1. I spin up latest Nightly with the harapi branch and web-ext (`web-ext run --firefox=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin --verbose`) 
2. I open the console and hit network tab and then go back to the console.
3. I access https://en.wikipedia.org/wiki/Barack_Obama, wait for the page to finished loading and then run 
```
HAR.triggerExport().then(harLog => {
  console.log(harLog);
});

``` 

in the console. It takes up to a minute for the HAR to be generated. If I try a page with fewer requests like https://www.wikipedia.org/ it still can take 10-15 seconds for the HAR promise to resolve.

Have you experienced the same? 

Best
Peter

**Comment by janodvarko** [comment]
Yes, this is known issue and on my TODO list (it's slow because of unnecessary timeouts)

It's reported here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1434855

Honza

**Comment by soulgalore** [comment]
Ok. This is a real killer for us. We run Firefox together with WebPageReplay to measure the front end performance and today we lack the HAR file. We do it for a couple of URLs with different RTT, and then  graph it here: https://grafana.wikimedia.org/dashboard/db/webpagereplay

The problem is that we do 11 runs per URL, so right now when it takes aprox 60s to get one HAR, it will add 11 minutes extra time per URL that we test with Firefox.

**Comment by janodvarko** [comment]
It's on top of my TODO list.
Honza

**Comment by janodvarko** [comment]
The following bug has been fixed in Firefox 60, so I am closing this issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1434855

Honza
