### ISSUE TITLE
Unable to access `HAR` from another extension

### ISSUE THREAD

**Issue by mizlan** [devtools-html/har-export-trigger#46]
I want to use `HAR.triggerExport()` from another Firefox extension but it doesn't seem to be defined. Is this a problem with the order in which the scripts load? Once I open up the debug console, I can use HAR just fine.

**Comment by janodvarko** [comment]
Yes, the DevTools Toolbox needs to be opened in order for this extension to work (i.e. the `HAR` object accessible)

Btw. you can use `--devtools` command line argument when launching Firefox to make sure that the Toolbox is opened automatically.

**Comment by mizlan** [comment]
I'm not too sure what you mean. Here is what I experienced:

1. I load my unpacked extension
2. I go to a website of interest
3. My extension loads but fails to see the `HAR` object
4. I open up DevTools, my extension still doesn't work but I can access `HAR` from the console
5. If I go to about:debugging and reload my unpacked extension, my extension script re-runs in my website page but `HAR` is still inaccessible, despite the DevTools being open

**Comment by janodvarko** [comment]
Can you please try the following:

1. Load http://softwareishard.com/test/harexporttrigger/
2. Open DevTools and Select the Network panel
3. Click on the `Text` button on the page
4. Click on the `getHar` button on the page
5. Check out the Console panel it should say `Done!` followed by the HAR log data

This works for me, does it work for you?

**Comment by mizlan** [comment]
It works for me. In case I didn't make it clear, I *am* able to access the HAR log data when I open DevTools and use `HAR.triggerExport()` by typing it in the console. By the way, you may not have understood my original question. I am writing *another* extension, and inside that extension I want to use `getHar`. I am wondering if this is possible.

**Comment by janodvarko** [comment]
Ah, sorry yes I misunderstood the original question. The `HAR` API are available only in DevTools scope, which is activated when DevTools Toolbox is opened.

You might checkout these places:
* https://github.com/firefox-devtools/har-export-trigger/blob/master/manifest.json#L6 (loaded when DevTools Toolbox is opened)
* https://github.com/firefox-devtools/har-export-trigger/blob/master/src/devtools.html#L10 (loads a script file)
* https://github.com/firefox-devtools/har-export-trigger/blob/master/src/devtools.js#L63 (an example of how you can access `getHar`)

Does that make sense?

**Comment by mizlan** [comment]
This is very helpful, thank you! So the idea would be to take the relevant parts of the code in this extension and repurpose it for my needs?

**Comment by janodvarko** [comment]
Yes, feel free to take/copy any piece of code from this extension.

Should we close this report?
