### ISSUE TITLE
could you provide a screenshot of what it is supposed to look like?

### ISSUE THREAD

**Issue by waifwaif** [devtools-html/har-export-trigger#6]
![ff](https://user-images.githubusercontent.com/36819736/36646440-6bd48e38-1a45-11e8-8be6-f5af08d6f358.png)

i'm not used to using firefox and i can't seem to get this to load, thank you

**Comment by xmhubj** [comment]
Not quite understand what kinds of screenshot you are looking for, when you enter `about:addons` in the navigation bar, you should be able see a page like this:

![addons_page](https://user-images.githubusercontent.com/15373664/36683769-69358046-1b59-11e8-8f24-8576b6b9fc93.jpg)

or if `about:debugging#addons` entered, you should see a page like this:

![debugging_page](https://user-images.githubusercontent.com/15373664/36683821-9588f29a-1b59-11e8-8c1c-85bcca5a397f.jpg)

**Comment by waifwaif** [comment]
sorry I mean in devtools

**Comment by xmhubj** [comment]
please take a look at issue 7, or issue 1, there are a few screenshots in the issues.
